services:
  - type: web
    name: your-django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        generateValue: true
